version: '3.9'
services:
  webapp:
    build:
      args:
        - PIP_VERSION=${WEBAPP_PIP_VERSION:-23.1.2}
        - POETRY_VERSION=${WEBAPP_POETRY_VERSION:-1.4.2}
        - PYTHON_VERSION=${WEBAPP_PYTHON_VERSION:-3.11}
        - VERSION=${WEBAPP_VERSION:-dev}
      context: .
    container_name: webapp
    entrypoint:
      - sh
      - -c
      - |
        python authentication/manage.py migrate 
        python authentication/manage.py runserver
    image: webapp:latest
    networks:
      - iteen
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/:ro
networks:
  iteen:
    name: iteen.network
    driver: bridge